# Generated by Django 6.0.7 on 2026-08-14 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_projudi_password'),
        ('projudi', '0012_movimentacaorecord_localizador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(help_text='Ex: Confraternização Universal, Carnaval, Sexta Santa', max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo (todo ano)'), ('unico', 'Data única (ano específico)'), ('movel', 'Móvel (data calculada por ano)')], default='fixo', max_length=10, verbose_name='Tipo')),
                ('escopo', models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual (BA)'), ('comarca', 'Comarca'), ('vara', 'Vara específica')], default='nacional', max_length=10, verbose_name='Escopo')),
                ('data', models.DateField(blank=True, help_text='Obrigatória p/ tipos "unico" e "movel". Ignorada em "fixo".', null=True, verbose_name='Data')),
                ('mes', models.PositiveSmallIntegerField(blank=True, help_text='Obrigatório p/ "fixo" (1-12).', null=True, verbose_name='Mês')),
                ('dia', models.PositiveSmallIntegerField(blank=True, help_text='Obrigatório p/ "fixo" (1-31).', null=True, verbose_name='Dia')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('court', models.ForeignKey(blank=True, help_text='Usar p/ escopo=estadual/comarca/vara.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='projudi.court')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('vara', models.ForeignKey(blank=True, help_text='Usar p/ escopo=vara.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='projudi.vara')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['tipo', 'mes', 'dia', 'data'],
            },
        ),
        migrations.CreateModel(
            name='SuspensaoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nome', models.CharField(help_text='Ex: Ponto Facultativo, Greve Geral, Recesso Comarca X', max_length=120, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('ponto_facultativo', 'Ponto Facultativo'), ('greve', 'Greve / Paralisação'), ('recesso_local', 'Recesso Local'), ('baixa', 'Semana de Baixa'), ('outro', 'Outro')], default='ponto_facultativo', max_length=20, verbose_name='Tipo')),
                ('escopo', models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual (BA)'), ('comarca', 'Comarca'), ('vara', 'Vara específica')], default='nacional', max_length=10, verbose_name='Escopo')),
                ('data_inicio', models.DateField(verbose_name='Data Início (inclusive)')),
                ('data_fim', models.DateField(verbose_name='Data Fim (inclusive)')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('court', models.ForeignKey(blank=True, help_text='Usar p/ escopo=estadual/comarca/vara.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_prazo', to='projudi.court')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('vara', models.ForeignKey(blank=True, help_text='Usar p/ escopo=vara.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspensoes_prazo', to='projudi.vara')),
            ],
            options={
                'verbose_name': 'Suspensão de Prazo',
                'verbose_name_plural': 'Suspensões de Prazo',
                'ordering': ['data_inicio'],
            },
        ),
    ]
