# Generated by Django 6.0.7 on 2026-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0013_feriado_suspensaoprazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumprimentorecord',
            name='observacao_prazo',
            field=models.TextField(blank=True, help_text='Texto controlado gerado a partir de prazo_info, usado na observação do Mov581 e/ou na certidão.', verbose_name='Observação de Prazo'),
        ),
        migrations.AddField(
            model_name='cumprimentorecord',
            name='prazo_info',
            field=models.JSONField(blank=True, default=dict, help_text='Resultado serializável do PrazoService (último dia, decurso, dias contados/excluídos, modo, djen).', verbose_name='Análise de Prazo (JSON)'),
        ),
    ]
