# Generated by Django 6.0.7 on 2026-07-09 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('state', models.CharField(default='BA', max_length=2, verbose_name='Estado')),
                ('projudi_url', models.URLField(blank=True, verbose_name='URL Projudi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Tribunal',
                'verbose_name_plural': 'Tribunais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjudiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cookies', models.JSONField(default=dict, verbose_name='Cookies')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('invalid', 'Inválida')], default='active', max_length=20, verbose_name='Status')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Última atividade')),
                ('session_data', models.JSONField(default=dict, verbose_name='Dados da sessão')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projudi_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Projudi',
                'verbose_name_plural': 'Sessões Projudi',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Vara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('comarca', models.CharField(max_length=200, verbose_name='Comarca')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varas', to='projudi.court')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Vara',
                'verbose_name_plural': 'Varas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('vara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='projudi.vara')),
            ],
            options={
                'verbose_name': 'Juiz',
                'verbose_name_plural': 'Juízes',
                'ordering': ['name'],
            },
        ),
    ]
