# Generated by Django 6.0.7 on 2026-07-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OficioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.CharField(db_index=True, max_length=30, verbose_name='Processo')),
                ('numero_oficio', models.CharField(db_index=True, max_length=50, verbose_name='Número Ofício')),
                ('email_destino', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Destino')),
                ('assunto', models.CharField(blank=True, max_length=300, verbose_name='Assunto')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('juntado', 'Juntado'), ('falhou_email', 'Falha no E-mail'), ('falhou_juntada', 'Falha na Juntada'), ('ignorado', 'Ignorado')], default='pendente', max_length=20, verbose_name='Status')),
                ('url_oficio', models.URLField(blank=True, verbose_name='URL Ofício')),
                ('url_processo', models.URLField(blank=True, verbose_name='URL Processo')),
                ('url_recebimento', models.URLField(blank=True, verbose_name='URL Recebimento')),
                ('url_baixa', models.URLField(blank=True, verbose_name='URL Baixa')),
                ('msg_id', models.CharField(blank=True, max_length=200, verbose_name='Message-ID')),
                ('data_envio', models.DateField(blank=True, null=True, verbose_name='Data Envio')),
                ('hora_envio', models.TimeField(blank=True, null=True, verbose_name='Hora Envio')),
                ('texto_html', models.TextField(blank=True, verbose_name='HTML Ofício')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_executados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ofício',
                'verbose_name_plural': 'Ofícios',
                'ordering': ['-created_at'],
                'unique_together': {('processo', 'numero_oficio')},
            },
        ),
        migrations.CreateModel(
            name='OficioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('envio', 'Envio'), ('juntada', 'Juntada'), ('erro_email', 'Erro E-mail'), ('erro_juntada', 'Erro Juntada'), ('resposta', 'Resposta Recebida'), ('resumo', 'Resumo IA')], default='info', max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('oficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projudi.oficiorecord')),
            ],
            options={
                'verbose_name': 'Log de Ofício',
                'verbose_name_plural': 'Logs de Ofícios',
                'ordering': ['-created_at'],
            },
        ),
    ]
