# Generated by Django 6.0.7 on 2026-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0002_oficiorecord_oficiolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficiorecord',
            name='anexos_retorno',
            field=models.JSONField(blank=True, default=list, verbose_name='Anexos do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='assunto_retorno',
            field=models.CharField(blank=True, max_length=300, verbose_name='Assunto do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='conteudo_retorno',
            field=models.TextField(blank=True, verbose_name='Conteúdo do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='observacao_retorno',
            field=models.TextField(blank=True, verbose_name='Observação do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='remetente_retorno',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Remetente do Retorno'),
        ),
        migrations.AddField(
            model_name='oficiorecord',
            name='status_retorno',
            field=models.CharField(choices=[('sem_retorno', 'Sem Retorno'), ('recebido', 'Recebido'), ('lido', 'Lido'), ('processado', 'Processado'), ('pendente_acao', 'Pendente de Ação')], default='sem_retorno', max_length=20, verbose_name='Status do Retorno'),
        ),
    ]
