# Generated by Django 6.0.7 on 2026-07-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('projudi', '0003_oficiorecord_anexos_retorno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projudisession',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projudi_sessions', to='accounts.tenant'),
        ),
    ]
