# Generated by Django 6.0.7 on 2026-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0004_alter_projudisession_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficiorecord',
            name='numero_processo_cnj',
            field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Nº Processo (CNJ)'),
        ),
        migrations.AlterField(
            model_name='oficiorecord',
            name='processo',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Processo (Interno)'),
        ),
    ]
