# Generated by Django 6.0.7 on 2026-07-14 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0005_oficiorecord_numero_processo_cnj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiolog',
            name='oficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projudi.oficiorecord'),
        ),
    ]
