# Generated by Django 6.0.7 on 2026-07-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0006_alter_oficiolog_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficiorecord',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('juntado', 'Juntado'), ('falhou_email', 'Falha no E-mail'), ('falhou_juntada', 'Falha na Juntada'), ('ignorado', 'Ignorado'), ('dispensado', 'Dispensado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
