# Generated by Django 6.0.7 on 2026-07-20 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0007_alter_oficiorecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandadoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.CharField(db_index=True, max_length=30, verbose_name='Processo (Interno)')),
                ('numero_processo_cnj', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Nº Processo (CNJ)')),
                ('numero_mandado', models.CharField(db_index=True, max_length=50, verbose_name='Número Mandado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('expedido', 'Expedido'), ('juntado', 'Juntado'), ('falha', 'Falha'), ('dispensado', 'Dispensado')], default='pendente', max_length=20, verbose_name='Status')),
                ('url_mandado', models.URLField(blank=True, verbose_name='URL Mandado')),
                ('url_processo', models.URLField(blank=True, verbose_name='URL Processo')),
                ('parte_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Parte')),
                ('texto_html', models.TextField(blank=True, verbose_name='HTML Mandado')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandados_executados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mandado',
                'verbose_name_plural': 'Mandados',
                'ordering': ['-created_at'],
                'unique_together': {('processo', 'numero_mandado')},
            },
        ),
        migrations.CreateModel(
            name='MandadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('expedicao', 'Expedição'), ('juntada', 'Juntada'), ('erro', 'Erro')], default='info', max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('mandado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projudi.mandadorecord')),
            ],
            options={
                'verbose_name': 'Log de Mandado',
                'verbose_name_plural': 'Logs de Mandados',
                'ordering': ['-created_at'],
            },
        ),
    ]
