# Generated by Django 6.0.7 on 2026-07-23 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_alter_ragexample_cumprimentos_and_more'),
        ('projudi', '0008_mandadorecord_mandadolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CumprimentoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.CharField(db_index=True, max_length=30, verbose_name='Processo (Interno)')),
                ('numero_processo_cnj', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Nº Processo (CNJ)')),
                ('fluxo', models.CharField(choices=[('eletronico', 'Eletrônico (DJEN)'), ('advogado', 'Advogado Constituído'), ('email', 'E-mail'), ('email_condicional', 'E-mail Condicional'), ('ar', 'Aviso de Recebimento'), ('mandado', 'Mandado'), ('mandado_precatorio', 'Mandado Prec.'), ('edital', 'Edital'), ('movimentacao_simples', 'Movimentação Simples')], max_length=25, verbose_name='Fluxo')),
                ('fluxo_justificativa', models.TextField(blank=True, verbose_name='Justificativa do Fluxo')),
                ('parte_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Parte')),
                ('parte_papel', models.CharField(blank=True, max_length=20, verbose_name='Papel da Parte')),
                ('endereco_analisado', models.JSONField(blank=True, default=dict, verbose_name='Endereço Analisado')),
                ('act_verb', models.CharField(blank=True, max_length=50, verbose_name='Ato')),
                ('snippet', models.TextField(blank=True, verbose_name='Trecho da Decisão')),
                ('texto_html', models.TextField(blank=True, verbose_name='HTML Gerado')),
                ('url_processo', models.URLField(blank=True, max_length=500, verbose_name='URL Processo')),
                ('url_movimentacao', models.URLField(blank=True, max_length=500, verbose_name='URL Movimentação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('cumprido', 'Cumprido'), ('falha', 'Falha'), ('dispensado', 'Dispensado')], default='pendente', max_length=20, verbose_name='Status')),
                ('rag_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumprimentos_gerados', to='processes.ragexample')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumprimentos', to='processes.documenttemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cumprimentos_executados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cumprimento',
                'verbose_name_plural': 'Cumprimentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CumprimentoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('decisao', 'Decisão'), ('execucao', 'Execução'), ('erro', 'Erro')], default='info', max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('cumprimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projudi.cumprimentorecord')),
            ],
            options={
                'verbose_name': 'Log de Cumprimento',
                'verbose_name_plural': 'Logs de Cumprimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
