# Generated by Django 6.0.7 on 2026-07-23 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_alter_ragexample_cumprimentos_and_more'),
        ('projudi', '0009_cumprimentorecord_cumprimentolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.CharField(db_index=True, max_length=30, verbose_name='Processo (Interno)')),
                ('numero_processo_cnj', models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Nº Processo (CNJ)')),
                ('act_verb', models.CharField(blank=True, help_text='Ex: certifique-se, arquive-se, publique-se, registre-se', max_length=50, verbose_name='Ato')),
                ('categoria', models.CharField(choices=[('certidao', 'Certidão'), ('intimacao', 'Intimação'), ('arquivamento', 'Arquivamento'), ('publicacao', 'Publicação'), ('registro', 'Registro'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Categoria')),
                ('observacao', models.TextField(blank=True, help_text='Texto a ser registrado como observação da movimentação', verbose_name='Observação')),
                ('parte_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Parte')),
                ('parte_papel', models.CharField(blank=True, max_length=20, verbose_name='Papel da Parte')),
                ('url_processo', models.URLField(blank=True, max_length=500, verbose_name='URL Processo')),
                ('url_movimentacao', models.URLField(blank=True, max_length=500, verbose_name='URL Movimentação')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('cumprido', 'Cumprido'), ('falha', 'Falha'), ('dispensado', 'Dispensado')], default='pendente', max_length=20, verbose_name='Status')),
                ('rag_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_geradas', to='processes.ragexample')),
                ('template_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='processes.documenttemplate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_executadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('info', 'Info'), ('execucao', 'Execução'), ('erro', 'Erro')], default='info', max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='projudi.movimentacaorecord')),
            ],
            options={
                'verbose_name': 'Log de Movimentação',
                'verbose_name_plural': 'Logs de Movimentações',
                'ordering': ['-created_at'],
            },
        ),
    ]
