# Generated by Django 6.0.7 on 2026-07-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projudi', '0010_movimentacaorecord_movimentacaolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaorecord',
            name='codigo_movimentacao',
            field=models.CharField(default='581', help_text='Código da categoria no Projudi (ex: 581 = TD - Tipo Documental)', max_length=10, verbose_name='Código Mov.'),
        ),
        migrations.AddField(
            model_name='movimentacaorecord',
            name='descricao_movimentacao',
            field=models.CharField(default='Cumprimento de Decisão', help_text='Descrição que aparece no campo descCategoriaMovimentacao do Projudi', max_length=100, verbose_name='Descrição Mov.'),
        ),
    ]
