# Generated by Django 6.0.7 on 2026-07-09 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('projudi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('number_normalized', models.CharField(max_length=50, verbose_name='Número Normalizado')),
                ('status', models.CharField(choices=[('distributed', 'Distribuído'), ('analyzing', 'Em Análise'), ('pending_compliance', 'Aguardando Cumprimento'), ('complied', 'Cumprido'), ('document_sent', 'Ofício Expedido'), ('closed', 'Encerrado')], default='distributed', max_length=30, verbose_name='Status')),
                ('class_processual', models.CharField(blank=True, max_length=100, verbose_name='Classe Processual')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Assunto')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da causa')),
                ('distribution_date', models.DateField(blank=True, null=True, verbose_name='Data de distribuição')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumo IA')),
                ('projudi_url', models.URLField(blank=True, max_length=500, verbose_name='URL Projudi')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_processes', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='projudi.court')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='projudi.judge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('vara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='projudi.vara')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('name_normalized', models.CharField(blank=True, max_length=200, verbose_name='Nome Normalizado')),
                ('role', models.CharField(choices=[('autor', 'Autor'), ('reu', 'Réu'), ('exequente', 'Exequente'), ('executado', 'Executado'), ('terceiro', 'Terceiro Interessado')], max_length=20, verbose_name='Papel')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('cpf_cnpj_encrypted', models.CharField(blank=True, max_length=200, verbose_name='CPF/CNPJ Criptografado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('has_lawyer', models.BooleanField(default=False, verbose_name='Tem advogado')),
                ('lawyer_name', models.CharField(blank=True, max_length=200, verbose_name='Advogado')),
                ('receives_email_intimation', models.BooleanField(default=False, verbose_name='Recebe intimação por email')),
                ('has_domicilio_cnj', models.BooleanField(default=False, verbose_name='Domicílio CNJ')),
                ('is_revel', models.BooleanField(default=False, verbose_name='Revel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='processes.process')),
            ],
            options={
                'verbose_name': 'Parte',
                'verbose_name_plural': 'Partes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_number', models.CharField(max_length=20, verbose_name='Evento')),
                ('act_description', models.TextField(verbose_name='Descrição do Ato')),
                ('act_normalized', models.TextField(blank=True, verbose_name='Ato Normalizado')),
                ('category', models.CharField(blank=True, choices=[('citacao', 'Citação'), ('intimacao', 'Intimação'), ('audiencia', 'Audiência'), ('sentenca', 'Sentença'), ('despacho', 'Despacho'), ('decisao', 'Decisão'), ('peticao', 'Petição'), ('certidao', 'Certidão'), ('ato_ordinatorio', 'Ato Ordinatório'), ('recurso', 'Recurso'), ('outro', 'Outro')], max_length=30, verbose_name='Categoria')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='Data do Ato')),
                ('reading_date', models.DateField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('reference_date', models.DateField(blank=True, null=True, verbose_name='Data de Referência')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='Autor')),
                ('communication_status', models.CharField(blank=True, choices=[('expedida', 'Expedida'), ('lida', 'Lida'), ('realizada', 'Realizada'), ('pendente', 'Pendente')], max_length=20, verbose_name='Status Comunicação')),
                ('communication_means', models.CharField(blank=True, choices=[('domicilio_cnj', 'Domicílio CNJ'), ('mandado', 'Mandado'), ('ar', 'Aviso de Recebimento'), ('precatoria', 'Precatória'), ('email', 'Email'), ('outro', 'Outro')], max_length=20, verbose_name='Meio de Comunicação')),
                ('recipient', models.CharField(blank=True, max_length=200, verbose_name='Destinatário')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('deadline_days', models.IntegerField(blank=True, null=True, verbose_name='Prazo (dias)')),
                ('deadline_date', models.DateField(blank=True, null=True, verbose_name='Data do Prazo')),
                ('referenced_event', models.CharField(blank=True, max_length=200, verbose_name='Evento Referenciado')),
                ('document_url', models.URLField(blank=True, max_length=500, verbose_name='URL Documento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='processes.process')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-act_date', '-event_number'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('prescricao', 'Prescrição'), ('decadencia', 'Decadência'), ('audiencia', 'Audiência'), ('recurso', 'Prazo Recursal'), ('intimacao', 'Intimação'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('expired', 'Expirado')], default='pending', max_length=20, verbose_name='Status')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deadlines', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deadlines', to='processes.movement')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='processes.process')),
            ],
            options={
                'verbose_name': 'Prazo',
                'verbose_name_plural': 'Prazos',
                'ordering': ['due_date'],
            },
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['number'], name='processes_p_number_a51b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['number_normalized'], name='processes_p_number__686309_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['status'], name='processes_p_status_cdc34b_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['process', 'event_number'], name='processes_m_process_74a754_idx'),
        ),
        migrations.AddIndex(
            model_name='movement',
            index=models.Index(fields=['category'], name='processes_m_categor_a5b01f_idx'),
        ),
    ]
