# Generated by Django 6.0.7 on 2026-07-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='referenced_event_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='processes.movement', verbose_name='Movimentação Referenciada'),
        ),
        migrations.CreateModel(
            name='MovementCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act_verb', models.CharField(max_length=50, verbose_name='Ato')),
                ('is_completable', models.BooleanField(default=False, verbose_name='Cumprivel')),
                ('recipient', models.JSONField(default=list, verbose_name='Destinatarios')),
                ('means', models.JSONField(default=list, verbose_name='Meios')),
                ('objective', models.JSONField(default=list, verbose_name='Objetivos')),
                ('deadline', models.JSONField(default=list, verbose_name='Prazos')),
                ('conditions', models.JSONField(default=list, verbose_name='Condicoes')),
                ('snippet', models.TextField(blank=True, verbose_name='Trecho')),
                ('has_costs', models.BooleanField(default=False, verbose_name='Tem custas')),
                ('costs_text', models.TextField(blank=True, verbose_name='Texto custas')),
                ('extracted_at', models.DateTimeField(auto_now_add=True, verbose_name='Extraido em')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='processes.movement')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_commands', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Comando de Movimentacao',
                'verbose_name_plural': 'Comandos de Movimentacoes',
                'ordering': ['-extracted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_automatable', models.BooleanField(default=False, verbose_name='Automatizavel')),
                ('automation_status', models.CharField(default='nao_analisado', max_length=30, verbose_name='Status Automacao')),
                ('total_movements', models.IntegerField(default=0, verbose_name='Total Movimentacoes')),
                ('total_commands', models.IntegerField(default=0, verbose_name='Total Comandos')),
                ('completable_commands', models.IntegerField(default=0, verbose_name='Comandos Cumpriveis')),
                ('tracked_communications', models.IntegerField(default=0, verbose_name='Comunicacoes Rastreadas')),
                ('pending_deadlines', models.IntegerField(default=0, verbose_name='Prazos Pendentes')),
                ('last_analysis', models.DateTimeField(blank=True, null=True, verbose_name='Ultima Analise')),
                ('has_advogado', models.BooleanField(default=False, verbose_name='Tem Advogado')),
                ('has_domicilio_cnj', models.BooleanField(default=False, verbose_name='Domicilio CNJ')),
                ('has_email', models.BooleanField(default=False, verbose_name='Email')),
                ('channels_summary', models.JSONField(default=dict, verbose_name='Resumo Canais')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='processes.process')),
            ],
            options={
                'verbose_name': 'Resumo do Processo',
                'verbose_name_plural': 'Resumos dos Processos',
            },
        ),
        migrations.CreateModel(
            name='CommunicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('intimacao', 'Intimacao'), ('citacao', 'Citacao'), ('mandado', 'Mandado'), ('certidao', 'Certidao'), ('ar', 'Aviso de Recebimento'), ('oficio', 'Oficio'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo')),
                ('event_expedido', models.CharField(max_length=10, verbose_name='Evento Expedido')),
                ('date_expedido', models.DateField(verbose_name='Data Expedicao')),
                ('act_expedido', models.TextField(verbose_name='Ato Expedido')),
                ('recipient', models.CharField(max_length=300, verbose_name='Destinatario')),
                ('means', models.CharField(blank=True, max_length=30, verbose_name='Meio')),
                ('event_lido', models.CharField(blank=True, max_length=10, verbose_name='Evento Lido')),
                ('date_lido', models.DateField(blank=True, null=True, verbose_name='Data Leitura')),
                ('status', models.CharField(choices=[('lida', 'Lida'), ('devolvida_sem_leitura', 'Devolvida sem leitura'), ('ar_juntado', 'AR juntado'), ('mandado_devolvido', 'Mandado devolvido'), ('mandado_assinado', 'Mandado assinado'), ('pendente', 'Pendente')], default='pendente', max_length=30, verbose_name='Status')),
                ('deadline_days', models.IntegerField(blank=True, null=True, verbose_name='Prazo (dias)')),
                ('deadline_expired', models.BooleanField(default=False, verbose_name='Prazo vencido')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='processes.process')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_trackings', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Rastreamento de Comunicacao',
                'verbose_name_plural': 'Rastreamentos de Comunicacoes',
                'ordering': ['-date_expedido'],
                'indexes': [models.Index(fields=['process', 'event_expedido'], name='processes_c_process_c78019_idx'), models.Index(fields=['status'], name='processes_c_status_6685fc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('act_type', models.CharField(max_length=50, verbose_name='Tipo Ato')),
                ('act_verb', models.CharField(max_length=50, verbose_name='Verbo')),
                ('recipient', models.CharField(max_length=300, verbose_name='Destinatario')),
                ('means_used', models.CharField(max_length=50, verbose_name='Meio Utilizado')),
                ('full_text', models.TextField(verbose_name='Texto Completo')),
                ('commands_json', models.JSONField(default=dict, verbose_name='Comandos JSON')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('email_to', models.EmailField(blank=True, max_length=254, verbose_name='Email Destino')),
                ('juntada_done', models.BooleanField(default=False, verbose_name='Juntada Realizada')),
                ('compliance_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Cumprimento')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='Embedding')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_history', to='processes.movement')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliances', to='processes.process')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_histories', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Cumprimento Historico',
                'verbose_name_plural': 'Cumprimentos Historicos',
                'ordering': ['-compliance_date'],
                'indexes': [models.Index(fields=['process', 'act_type'], name='processes_c_process_0c15b3_idx'), models.Index(fields=['means_used'], name='processes_c_means_u_3aedca_idx')],
            },
        ),
    ]
