# Generated by Django 6.0.7 on 2026-07-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_movement_referenced_event_obj_movementcommand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancehistory',
            name='active',
            field=models.BooleanField(default=True, help_text='Usar este registro como exemplo nas buscas RAG', verbose_name='Ativo p/ RAG'),
        ),
    ]
