# Generated by Django 6.0.7 on 2026-07-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('processes', '0003_compliancehistory_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficio', models.CharField(blank=True, max_length=50, verbose_name='Oficio')),
                ('despacho_ato', models.TextField(verbose_name='Decisao do Juiz')),
                ('despacho_data', models.CharField(blank=True, max_length=20, verbose_name='Data Despacho')),
                ('despacho_autor', models.CharField(blank=True, max_length=200, verbose_name='Juiz')),
                ('evento_despacho', models.CharField(blank=True, max_length=20, verbose_name='Evento Despacho')),
                ('cumprimentos', models.JSONField(default=list, help_text='Lista de dicts com ato, observacao, data, autor', verbose_name='Atos de Cumprimento')),
                ('active', models.BooleanField(default=True, help_text='Usar como exemplo nas buscas', verbose_name='Ativo p/ RAG')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rag_examples', to='processes.process')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_examples', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Exemplo RAG',
                'verbose_name_plural': 'Exemplos RAG',
                'ordering': ['-created_at'],
            },
        ),
    ]
