# Generated by Django 6.0.7 on 2026-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_ragexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragexample',
            name='despacho_observacao',
            field=models.TextField(blank=True, help_text='Texto completo da decisao/juntada do juiz', verbose_name='Observacao do Despacho'),
        ),
        migrations.AlterField(
            model_name='ragexample',
            name='cumprimentos',
            field=models.JSONField(default=list, help_text='Lista de dicts com ato, observacao, data, autor, tipo', verbose_name='Atos de Cumprimento'),
        ),
    ]
