# Generated by Django 6.0.7 on 2026-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_ragexample_despacho_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragexample',
            name='documentos',
            field=models.JSONField(default=list, help_text='Links para documentos/downloads do despacho', verbose_name='Documentos do Despacho'),
        ),
    ]
