# Generated by Django 6.0.7 on 2026-07-15 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('processes', '0006_ragexample_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Modelo')),
                ('template_type', models.CharField(choices=[('mandado', 'Mandado'), ('oficio', 'Ofício'), ('intimacao', 'Intimação'), ('certidao', 'Certidão'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, help_text='Quando usar este modelo? Ex: "Para ofícios ao banco com decisão de força de mandado"', verbose_name='Descrição')),
                ('html_template', models.TextField(help_text='HTML com placeholders {{ parte.nome }}, {{ processo }}, {{ despacho_observacao }}, etc.', verbose_name='Template HTML')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Modelo de Documento',
                'verbose_name_plural': 'Modelos de Documento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ragexample',
            name='suggested_templates',
            field=models.ManyToManyField(blank=True, help_text='Modelos de documento sugeridos para esta decisao', related_name='rag_examples', to='processes.documenttemplate'),
        ),
    ]
