# Generated by Django 6.0.7 on 2026-07-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_documenttemplate_ragexample_suggested_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='tenant',
        ),
    ]
