# Generated by Django 6.0.7 on 2026-07-15 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('processes', '0008_remove_documenttemplate_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequential_number', models.IntegerField(default=0, verbose_name='Número Sequencial')),
                ('year', models.IntegerField(default=0, verbose_name='Ano')),
                ('recipient_name', models.CharField(blank=True, max_length=300, verbose_name='Destinatário')),
                ('recipient_email', models.CharField(blank=True, max_length=200, verbose_name='Email')),
                ('html_content', models.TextField(blank=True, verbose_name='HTML Gerado')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='processes.process')),
                ('rag_example', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='processes.ragexample')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='processes.documenttemplate')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Documento Gerado',
                'verbose_name_plural': 'Documentos Gerados',
                'ordering': ['-year', '-sequential_number'],
                'unique_together': {('template', 'year', 'sequential_number')},
            },
        ),
    ]
