# Generated by Django 6.0.7 on 2026-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='party',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='party',
            name='rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='party',
            name='rg_encrypted',
            field=models.CharField(blank=True, max_length=200, verbose_name='RG Criptografado'),
        ),
    ]
