# Generated by Django 6.0.7 on 2026-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_party_nome_mae_party_nome_pai_party_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateddocument',
            name='exported_to_projudi',
            field=models.BooleanField(default=False, verbose_name='Exportado ao Projudi'),
        ),
    ]
