# Generated by Django 6.0.7 on 2026-07-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_generateddocument_exported_to_projudi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragexample',
            name='cumprimentos',
            field=models.JSONField(blank=True, default=list, help_text='Lista de dicts com ato, observacao, data, autor, tipo', verbose_name='Atos de Cumprimento'),
        ),
        migrations.AlterField(
            model_name='ragexample',
            name='documentos',
            field=models.JSONField(blank=True, default=list, help_text='Links para documentos/downloads do despacho', verbose_name='Documentos do Despacho'),
        ),
    ]
