# Generated by Django 6.0.7 on 2026-07-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_alter_ragexample_cumprimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragexample',
            name='sequencia_cumprimento',
            field=models.JSONField(blank=True, default=list, help_text='Lista ORDENADA de atos a executar quando este RAGExample for match. Cada item da lista é um dict:\n- {"tipo": "movimentacao", "observacao": "texto..."}\n- {"tipo": "mandado", "template_id": 12}\n- {"tipo": "oficio", "template_id": 7}\n- {"tipo": "intimacao", "template_id": 5}\nA ordem da lista define a sequência de execução. Para movimentações, a "observacao" é o texto que será registrado no Projudi via Mov581.', verbose_name='Sequência de Execução'),
        ),
    ]
