# Generated by Django 6.0.7 on 2026-08-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_alter_ragexample_sequencia_cumprimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragexample',
            name='exigir_todas_frases',
            field=models.BooleanField(default=False, help_text='True = todas as frases devem estar no despacho (AND). False = qualquer uma bloqueia (OR).', verbose_name='Exigir todas as frases?'),
        ),
        migrations.AddField(
            model_name='ragexample',
            name='frases_bloqueio',
            field=models.JSONField(blank=True, default=list, help_text='Lista de FRASES determinísticas (substring) que, se presentes no despacho, BLOQUEIAM a execução (NÃO FAZER / NÃO CUMPRIR). Independente de contagem de palavras. Ex.: ["certifique-se sobre a tempestividade", "segredo de justiça"]. Se "exigir_todas_frases" for True, TODAS devem aparecer; senão, QUALQUER uma já bloqueia.', verbose_name='Frases Bloqueadoras'),
        ),
    ]
