# Generated by Django 6.0.7 on 2026-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projudi_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Senha Projudi'),
        ),
    ]
